# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OGFlushPlugin
                                 A QGIS plugin
 This plugin creates a sewer network from geodata
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-17
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Arbeitsgruppe Siedlungshydrologie, Institut für Siedlungs- und Industriewasserwirtschaft, Technische Universität Dresden
        email                : diego.novoa_vazquez@tu-dresden.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from PyQt5.QtWidgets import QMessageBox, QLabel
from qgis.core import QgsProject, QgsMapLayer, QgsWkbTypes, Qgis, QgsVectorLayer, QgsRasterLayer
from PyQt5.QtCore import Qt, QUrl

import locale, sys
import os, shutil

from .resources import *
from .og_flush_dialog import OGFlushPluginDialog


class OGFlushPlugin:

    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        # Initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'OGFlushPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&OG.FLUSH')
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        return QCoreApplication.translate('OGFlushPlugin', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/og_flush/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Design a Sewer Network'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&OG.FLUSH'),
                action)
            self.iface.removeToolBarIcon(action)

#%%

    def select_output_file(self):
        directory_url = QFileDialog.getExistingDirectoryUrl(
            self.dlg, self.tr("Select output directory"), QUrl())
        directory_path = directory_url.toLocalFile() if directory_url.isLocalFile() else ""
        self.dlg.output_name.setText(directory_path)

    def select_input_raster(self, combobox_name):
        filters = self.tr("Raster Files (*.tif *.asc *.bin);;All Files (*)")
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, self.tr("Select input raster"), "", filters)
        if filename:
            combobox_name.addItem(filename)
            index = combobox_name.findText(filename)
            combobox_name.setCurrentIndex(index)

    def select_input_shape(self, combobox_name):
        filename, _filter = QFileDialog.getOpenFileName(
            self.dlg, self.tr("Select input shapefile"), "", '*.shp')
        if filename:
            combobox_name.addItem(filename)
            index = combobox_name.findText(filename)
            combobox_name.setCurrentIndex(index)

    def add_selected_raster_layer(self, combobox_name):
        filename = combobox_name.currentText()
        raster_layer = QgsRasterLayer(filename, os.path.basename(filename), "gdal")
        if raster_layer.isValid():
            QgsProject.instance().addMapLayer(raster_layer)
            return raster_layer

    def add_selected_shape_layer(self, combobox_name):
        filename = combobox_name.currentText()
        vector_layer = QgsVectorLayer(filename, os.path.basename(filename), "ogr")
        if vector_layer.isValid():
            QgsProject.instance().addMapLayer(vector_layer)
            return vector_layer

    def connect_rasterbox_and_button(self, combobox, button):
        button.clicked.connect(lambda: self.select_input_raster(combobox))

    def connect_shapebox_and_button(self, combobox, button):
        button.clicked.connect(lambda: self.select_input_shape(combobox))

    def show_error_message(self, message):
        QMessageBox.critical(None, self.tr('Error'), message, QMessageBox.Ok)

    def cleanup_temp_files(self, temp_files, temp_folder):
        """Clean up temporary files and folders"""
        try:
            for file in temp_files:
                if os.path.exists(file):
                    os.remove(file)
            if os.path.exists(temp_folder):
                shutil.rmtree(temp_folder)
            print("Temporary files and folder removed.")
        except Exception as e:
            print(f"Error while cleaning up temporary files: {str(e)}")

    def reset_progress(self):
        """Reset progress bar and clear all dialog fields and references"""
        self.dlg.progressBar.setValue(0)
        self.dlg.progressBar.setVisible(False)
        self.processing_cancelled = False
        QCoreApplication.processEvents()
        self.run_completed = True

    def cancel_processing(self):
        """Set the cancel flag when user clicks cancel"""
        self.processing_cancelled = True
        QMessageBox.information(None,
                                self.tr("Processing Cancelled"),
                                self.tr("Processing has been cancelled by user."))

    def check_dependencies(self):
        missing_deps = []
        try:
            import numpy as np
        except ImportError:
            missing_deps.append("numpy")
        try:
            import pandas as pd
        except ImportError:
            missing_deps.append("pandas")
        try:
            import networkx as nx
        except ImportError:
            missing_deps.append("networkx")
        return missing_deps

#%%
    def run_button_clicked(self, rr):
        '''Main function'''
        self.reset_progress()
        self.dlg.Run_pb.setEnabled(False)

        try:
            self.dlg.progressBar.setVisible(True)
            self.dlg.progressBar.setMinimum(0)
            self.dlg.progressBar.setMaximum(100)
            self.dlg.progressBar.setValue(0)

            self.dlg.progressBar.setStyleSheet("""
                QProgressBar {
                    border: 1px solid #999999;
                    border-radius: 3px;
                    background-color: #f0f0f0;
                    text-align: center;
                    color: #333333;
                    font-weight: bold;
                }
                QProgressBar::chunk {
                    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                        stop:0 #4CAF50, stop:0.5 #66BB6A, stop:1 #4CAF50);
                    border-radius: 2px;
                }
            """)

            QCoreApplication.processEvents()

            missing_deps = self.check_dependencies()
            if missing_deps:
                lib_list = ", ".join(missing_deps)
                error_message = self.tr(
                    "Missing Required Dependencies: {lib_list}\n\n"
                    "This plugin requires the following Python libraries to function:\n"
                    "- numpy\n"
                    "- pandas\n"
                    "- networkx\n\n"
                    "Please install these dependencies following the installation guide "
                    "in the README and try again.\n"
                    "The instructions can be found in the plugin documentation by following "
                    "the link showed on the plugin UI."
                ).format(lib_list=lib_list)
                QMessageBox.critical(None, self.tr('Missing Dependencies'),
                                     error_message, QMessageBox.Ok)
                self.reset_progress()
                return

            self.processing_cancelled = False

            depth               = self.dlg.pipe_depth.value()
            min_slope           = self.dlg.min_slope_pipe.value()
            min_slope_buildings = self.dlg.build_min_sl.value()
            min_slope_streets   = self.dlg.st_min_slope.value()
            thr                 = self.dlg.dist_thresh.value()
            max_slope_buildings = self.dlg.build_max_slope.value()
            max_slope_streets   = self.dlg.st_max_sl.value()
            z                   = self.dlg.return_period.value()
            r15                 = self.dlg.r15_rain.value()
            Tfmin               = self.dlg.tf_min.value()
            fgw                 = self.dlg.consumption_perc.value()
            annual_pop_growth   = self.dlg.pop_grow.value()
            consumption         = self.dlg.consumption.value()
            years_pop           = self.dlg.years_growth.value()
            meshness_perc       = self.dlg.meshness_perc.value()

            min_slope = min_slope * 0.01
            qs = (consumption / 86400)

            combined = self.dlg.mixed_cb.isChecked()
            gw_inf   = self.dlg.gw_cb.isChecked()

            if gw_inf == False:
                fgw = 0

            sys.path.append(os.path.dirname(os.path.abspath(__file__)))
            sys.path.append(os.path.dirname(os.path.realpath(__file__)))
            os.chdir(os.path.dirname(os.path.realpath(__file__)))
            sys.path.append(os.path.dirname(os.path.abspath(__file__)))

            import numpy as np
            from . import functions_SG0 as sg0
            from . import functions_SG1 as sg1
            from . import functions_SG2 as sg2
            from . import functions_SG3 as sg3
            from . import functions_SG4 as sg4
            from . import functions_SG5 as sg5

            layers = QgsProject.instance().mapLayers().values()
            raster_layers = [layer for layer in layers
                             if layer.type() == QgsMapLayer.RasterLayer]
            raster_layers = [''] + raster_layers

            vector_layers = [layer for layer in layers
                             if layer.type() == QgsMapLayer.VectorLayer]

            point_layers = [layer for layer in vector_layers
                            if layer.geometryType() == QgsWkbTypes.PointGeometry]
            point_layers = [''] + point_layers

            line_layers = [layer for layer in vector_layers
                           if layer.geometryType() == QgsWkbTypes.LineGeometry]
            line_layers = [''] + line_layers

            poly_layers = [layer for layer in vector_layers
                           if layer.geometryType() == QgsWkbTypes.PolygonGeometry]
            poly_layers = [''] + poly_layers

            def sel_layer_r(box, layerlist):
                index = box.currentIndex()
                if index < len(layerlist):
                    sel = list(layerlist)[index]
                else:
                    sel = self.add_selected_raster_layer(box)
                return sel

            def sel_layer_s(box, layerlist):
                index = box.currentIndex()
                if index < len(layerlist):
                    sel = list(layerlist)[index]
                else:
                    sel = self.add_selected_shape_layer(box)
                return sel

            dem          = sel_layer_r(self.dlg.dembox, raster_layers)
            streets_osm  = sel_layer_s(self.dlg.streetbox, line_layers)
            buildings    = sel_layer_s(self.dlg.buildbox, poly_layers)
            study_area   = sel_layer_s(self.dlg.catchbox, poly_layers)
            outlet       = sel_layer_s(self.dlg.outletbox, point_layers)
            output       = self.dlg.output_name.text()

            if not dem:
                self.show_error_message(self.tr("Please select a DEM layer."))
                return
            if not streets_osm:
                self.show_error_message(self.tr("Please select a Street layer."))
                return
            if not buildings:
                self.show_error_message(self.tr("Please select a Building layer."))
                return
            if not study_area:
                self.show_error_message(self.tr("Please select a Study Area/Catchment layer."))
                return
            if not outlet:
                self.show_error_message(self.tr("Please select an Outlet layer."))
                return

            if combined == True:
                pop_density = sel_layer_s(self.dlg.popbox, point_layers)
                if not pop_density:
                    self.show_error_message(self.tr("Please select a population density layer."))
                    return
            if not output:
                self.show_error_message(self.tr("Please select a location for your outputs."))
                return

            path_shapefiles = output

            crs = buildings.crs()
            epsg = crs.postgisSrid()
            crs = study_area.crs()
            epsg = [epsg, crs.postgisSrid()]
            crs = streets_osm.crs()
            epsg = epsg + [crs.postgisSrid()]
            crs = outlet.crs()
            epsg = epsg + [crs.postgisSrid()]
            crs = dem.crs()
            epsg = epsg + [crs.postgisSrid()]
            epsg = [x for x in epsg if x > 0]
            epsg = max(set(epsg), key=epsg.count)

            print(f"EPSG: {epsg}")

            group_name = "Sewer_Network_Data"
            root = QgsProject.instance().layerTreeRoot()
            group = root.findGroup(group_name)
            if not group:
                group = root.addGroup(group_name)

#%%
            buffer_threshold = 30
            distance = sg0.calculate_outlet_distance(outlet, study_area)
            if distance > buffer_threshold:
                raise Exception(
                    self.tr("Outlet too far: {dist:.2f}m from boundary (max: {max}m)").format(
                        dist=distance, max=buffer_threshold))

            snap_out, temp_connected_streets = sg1.clip_streets(streets_osm, study_area, outlet)
            connected_streets_nodes, connected_streets, out_final = sg1.vertex_extraction(
                temp_connected_streets, dem, depth, snap_out)
            MST_streetsX = sg1.create_mst(out_final, connected_streets, connected_streets_nodes, epsg)
            MST_streets = sg1.MST_streets2(MST_streetsX, connected_streets_nodes)

            self.dlg.progressBar.setValue(10)
            QCoreApplication.processEvents()

            df_links  = sg1.shapefile_to_dataframe(MST_streets)
            df_nodes  = sg1.shapefile_to_dataframe(connected_streets_nodes)
            df_outlet = sg1.shapefile_to_dataframe(out_final)

            del snap_out, temp_connected_streets

            corr2 = sg1.correct_dir2(df_links, df_outlet)
            df_links, df_nodes = sg1.corr_elev_new(df_links, df_nodes, corr2, min_slope, df_outlet)

            selected_columns = ['LINK_ID', 'FROM_node', 'TO_node']
            corr_dir = df_links[selected_columns].values
            base_sewer = sg1.get_base_sewer(MST_streets, corr_dir)

            selected_columns = ['NODE_ID', 'x', 'y', 'invert_elev']
            inv_elev = df_nodes[selected_columns].values
            base_sewer_nodes = sg1.get_sewer_nodes(inv_elev, connected_streets_nodes)
            outfall = sg1.update_outlet(out_final, base_sewer_nodes)

            self.dlg.progressBar.setValue(25)
            QCoreApplication.processEvents()

            slope_limits = {
                'min_slope_buildings': min_slope_buildings,
                'max_slope_buildings': max_slope_buildings,
                'min_slope_streets': min_slope_streets,
                'max_slope_streets': max_slope_streets
            }

            connected_buildings = sg2.process_buildings(
                buildings, study_area, base_sewer, base_sewer_nodes,
                dem, slope_limits, thr, 'BU')

            sg1.save_to_disk(connected_buildings,
                             os.path.join(path_shapefiles, 'Connected_Buildings.shp'))
            connected_buildings = QgsVectorLayer(
                os.path.join(path_shapefiles, 'Connected_Buildings.shp'),
                "Connected_Buildings", "ogr")
            QgsProject.instance().addMapLayer(connected_buildings, False)
            group.addLayer(connected_buildings)

            connected_street_areas = sg2.process_streets(
                connected_streets, base_sewer_nodes, dem, slope_limits, 'ST')
            sg1.save_to_disk(connected_street_areas,
                             os.path.join(path_shapefiles, 'Connected_Street_Areas.shp'))
            connected_street_areas = QgsVectorLayer(
                os.path.join(path_shapefiles, 'Connected_Street_Areas.shp'),
                "Connected_Street_Areas", "ogr")
            QgsProject.instance().addMapLayer(connected_street_areas, False)
            group.addLayer(connected_street_areas)

            if combined == 1:
                population_density = sg2.process_population(
                    pop_density, connected_buildings, annual_pop_growth, years_pop)

            self.dlg.progressBar.setValue(50)
            QCoreApplication.processEvents()

            pipes_array = sg2.shapefile_to_array(base_sewer)
            nodes_array = sg2.shapefile_to_array(base_sewer_nodes)
            connected_buildings_array = sg2.shapefile_to_array(connected_buildings)
            connected_street_areas_array = sg2.shapefile_to_array(connected_street_areas)

            max_depth = nodes_array[:, 3] - nodes_array[:, 4]
            new_nodes_array = np.column_stack((nodes_array, max_depth))
            nodes_array = node_design_data = new_nodes_array

            pipe_design_data = sg2.process_pipe_data(
                pipes_array, nodes_array,
                os.path.join(path_shapefiles, 'pipe_data_design.csv'))

            pop_data = None
            if combined:
                pop_data = sg2.shapefile_to_array(population_density)

            subcatchment_design_data = sg2.process_subcatchments(
                connected_buildings_array, connected_street_areas_array,
                slope_limits, combined, pop_data)

            nodedf, pipedf, subdf = sg2.design_data(
                node_design_data, pipe_design_data, subcatchment_design_data,
                path_shapefiles, save_csv=True)

            self.dlg.progressBar.setValue(70)
            QCoreApplication.processEvents()

            number_it = 1
            head, pipe_dim, subdf2 = sg3.pipe_dim_prep(
                pipedf, subdf, sg3.psit, r15, qs, fgw, Tfmin, z, number_it)
            number_it = number_it + 1
            lastiter = head
            pipe_dim = sg3.pipe_dimension(pipe_dim, lastiter, subdf2, Tfmin, z, r15, number_it)
            pipe_dim = pipe_dim.rename(columns={'D': 'Diameter'})

            pipe_dim.to_csv(os.path.join(path_shapefiles, 'Total_results_gw.csv'), index=True)

            pipe_dim2 = pipe_dim.drop(columns=[
                'cumQ', 'Qtot', 'it', 'sqdw', 'cuml', 'qdw', 'qgw',
                'sqgw', 'Qmax', 'sumtf', 'okqdw', 'cumd'])

            head = head.rename(columns={'D': 'Diameter'})
            base_sewer_joined = sg1.join_designed_data(base_sewer, pipe_dim2)

            self.dlg.progressBar.setValue(90)
            QCoreApplication.processEvents()

            if meshness_perc > 0:
                skipped_streets = sg4.extract_skipped_streets(connected_streets, MST_streets)
                skipped_streets_with_fields = sg1.MST_streets2(skipped_streets, connected_streets_nodes)
                skipped_links = sg4.correct_node_elevations(skipped_streets_with_fields, base_sewer_nodes)
                skipped_links_with_more_info = sg4.add_further_data_to_links(skipped_links, pipe_dim, head)
                skipped_links_sorted = sg4.sort_features(skipped_links_with_more_info)
            else:
                skipped_links_sorted = None

            designed_sewer_network = sg4.add_skipped_links_to_designed(
                base_sewer_joined, skipped_links_sorted, meshness_perc)
            sg1.save_to_disk(designed_sewer_network,
                             os.path.join(path_shapefiles, 'Designed_Sewer_Network.shp'))
            sg1.save_to_disk(base_sewer_nodes,
                             os.path.join(path_shapefiles, 'Base_Sewer_Nodes.shp'))
            sg1.save_to_disk(outfall, os.path.join(path_shapefiles, 'Outfall.shp'))

            base_sewer_nodes = QgsVectorLayer(
                os.path.join(path_shapefiles, 'base_sewer_Nodes.shp'),
                "Base_Sewer_Nodes", "ogr")
            outfall = QgsVectorLayer(
                os.path.join(path_shapefiles, 'Outfall.shp'), "Outfall", "ogr")
            designed_sewer_network = QgsVectorLayer(
                os.path.join(path_shapefiles, 'Designed_Sewer_Network.shp'),
                "Designed_Sewer_Network", "ogr")

            QgsProject.instance().addMapLayer(base_sewer_nodes, False)
            QgsProject.instance().addMapLayer(outfall, False)
            QgsProject.instance().addMapLayer(designed_sewer_network, False)

            group.addLayer(base_sewer_nodes)
            group.addLayer(outfall)
            group.addLayer(designed_sewer_network)

            pipe_result = sg2.shapefile_to_dataframe(designed_sewer_network)
            pipe_result.to_csv(os.path.join(path_shapefiles, 'pipe_result.csv'), index=False)

            self.dlg.progressBar.setValue(95)
            QCoreApplication.processEvents()

            links_array    = pipe_result.to_numpy()
            outfall_array  = sg2.shapefile_to_array(outfall)

            inp_config = {
                'nodes_array': nodes_array,
                'links_array': links_array,
                'outfall_array': outfall_array,
                'building_layer': connected_buildings,
                'street_layer': connected_street_areas,
                'model_path': path_shapefiles,
                'min_slope_buildings': min_slope_buildings,
                'max_slope_buildings': max_slope_buildings,
                'min_slope_streets': min_slope_streets,
                'max_slope_streets': max_slope_streets
            }

            output_file_path = sg5.create_swmm_model(inp_config)

            if output_file_path:
                print(f"SWMM model file successfully created at {output_file_path}")
            else:
                print("Failed to write SWMM model file. Check logs for details.")

            self.dlg.progressBar.setValue(100)
            QCoreApplication.processEvents()

            self.iface.messageBar().pushMessage(
                self.tr("Success"),
                self.tr("Output files successfully created"),
                level=Qgis.Success, duration=3)
            print("Processing has been completed.")

        except Exception as e:
            error_msg = self.tr("An error occurred during processing: {error}").format(
                error=str(e))
            self.show_error_message(error_msg)
            print(f"Error in run_button_clicked: {str(e)}")

        finally:
            self.dlg.Run_pb.setEnabled(True)

        return

#%%

    def run(self):
        """Run method that performs all the real work"""
        locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

        if self.first_start == True:
            self.first_start = False
            self.dlg = OGFlushPluginDialog()

            label = self.dlg.findChild(QLabel, "label_5")
            if label:
                label.setOpenExternalLinks(True)
                label.setTextInteractionFlags(Qt.TextBrowserInteraction)

            self.dlg.pb_output.clicked.connect(self.select_output_file)

            self.connect_rasterbox_and_button(self.dlg.dembox, self.dlg.pb_DEM)
            self.connect_shapebox_and_button(self.dlg.popbox, self.dlg.pb_pop)
            self.connect_shapebox_and_button(self.dlg.buildbox, self.dlg.pb_build)
            self.connect_shapebox_and_button(self.dlg.streetbox, self.dlg.pb_st)
            self.connect_shapebox_and_button(self.dlg.catchbox, self.dlg.pb_catch)
            self.connect_shapebox_and_button(self.dlg.outletbox, self.dlg.pb_out)

            self.dlg.Run_pb.clicked.connect(self.run_button_clicked)

        layers = QgsProject.instance().mapLayers().values()
        raster_layers = [layer for layer in layers
                         if layer.type() == QgsMapLayer.RasterLayer]
        vector_layers = [layer for layer in layers
                         if layer.type() == QgsMapLayer.VectorLayer]
        point_layers = [layer for layer in vector_layers
                        if layer.geometryType() == QgsWkbTypes.PointGeometry]
        line_layers  = [layer for layer in vector_layers
                        if layer.geometryType() == QgsWkbTypes.LineGeometry]
        poly_layers  = [layer for layer in vector_layers
                        if layer.geometryType() == QgsWkbTypes.PolygonGeometry]

        raster_name = [''] + [layer.name() for layer in layers
                               if layer.type() == QgsMapLayer.RasterLayer]
        point_name  = [''] + [layer.name() for layer in vector_layers
                               if layer.geometryType() == QgsWkbTypes.PointGeometry]
        line_name   = [''] + [layer.name() for layer in vector_layers
                               if layer.geometryType() == QgsWkbTypes.LineGeometry]
        poly_name   = [''] + [layer.name() for layer in vector_layers
                               if layer.geometryType() == QgsWkbTypes.PolygonGeometry]

        self.dlg.dembox.clear()
        self.dlg.dembox.addItems(raster_name)

        self.dlg.buildbox.clear()
        self.dlg.buildbox.addItems(poly_name)

        self.dlg.streetbox.clear()
        self.dlg.streetbox.addItems(line_name)

        self.dlg.catchbox.clear()
        self.dlg.catchbox.addItems(poly_name)

        self.dlg.outletbox.clear()
        self.dlg.outletbox.addItems(point_name)

        self.dlg.popbox.clear()
        self.dlg.popbox.addItems(point_name)

        self.dlg.show()
        result = self.dlg.exec_()

        if result:
            pass
